const croDogMock = [
  [
    '1767',
    'Ração',
    ['Ração Seca', 'Ração Úmida', 'Ração Prescrita', 'Ração Natural'],
  ],
  [
    '1772',
    'Petiscos e Ossos',
    [
      'Palitos',
      'Bifinhos',
      'Biscoitos',
      'Bolos e Chocolates',
      'Bebidas e Molhos',
      'Ossinhos',
    ],
  ],
  [
    '1779',
    'Tapetes, Fraldas e Banheiros',
    ['Tapetes Higiênicos', 'Fraldas', 'Banheiros', 'Cones'],
  ],
  [
    '1784',
    'Farmácia',
    [
      'Antipulgas e Carrapatos',
      'Demais Medicamentos',
      'Anti-inflamatórios',
      'Antibióticos',
      'Suplementos e Vitaminas',
      'Vermífugos',
      'Homeopáticos e Florais',
      'Oftalmológicos',
      'Otológicos',
      'Cuidado Oral',
      'Banho Terapêutico',
      'Roupas Cirúrgicas',
      'Colares Elizabetanos',
    ],
  ],
  [
    '1798',
    'Brinquedos',
    [
      'Bichinhos de Pelúcia',
      'Bolinhas',
      'Brinquedos em Nylon',
      'Brinquedos Educativos',
      'Brinquedos de Corda',
      'Frisbees',
      'Mordedores',
    ],
  ],
  ['1806', 'Coleiras, Guias e Peitorais', ['Coleiras', 'Guias', 'Peitorais']],
  [
    '1811',
    'Beleza e Limpeza',
    [
      'Banho à Seco e Talcos',
      'Sabonetes',
      'Shampoos e Condicionadores',
      'Hidratantes',
      'Perfumes e Colônias',
      'Higiene Bucal',
      'Pentes, escovas e Rasqueadeiras',
      'Lenços Umedecidos',
      'Limpeza de Olhos e Ouvidos',
      'Máquina de Tosa e Acessórios',
      'Alicates e Tesouras',
      'Coletor de Fezes',
      'Eliminador de Odores e Desinfetantes',
      'Educadores, Repelentes e Atrativos',
    ],
  ],
  [
    '1826',
    'Camas e Cobertores',
    ['Almofadas e Colchonetes', 'Camas', 'Edredons, Cobertores e Mantas'],
  ],
  ['1830', 'Casas e Tocas', ['Casas', 'Tocas']],
  [
    '1833',
    'Acessórios de Alimentação',
    [
      'Fontes',
      'Dosadores de Ração',
      'Porta Ração',
      'Comedouros',
      'Bebedouros',
      'Jogo Americano',
      'Mamadeiras',
    ],
  ],
  [
    '1841',
    'Acessórios de Transporte',
    [
      'Caixas de Transporte',
      'Bolsas de Transporte',
      'Carrinhos',
      'Cintos de Segurança',
      'Cadeirinhas',
      'Capas para Banco de Carro',
    ],
  ],
  [
    '1848',
    'Portões, grades e Escadas',
    ['Portões', 'Grades', 'Canil', 'Portas', 'Escadas'],
  ],
  ['1854', 'Roupas', ['Roupas de Inverno', 'Roupas de Verão', 'Diversos']],
  [
    '1858',
    'Adestramento e Comportamento',
    ['Acessórios para Treinamento', 'Focinheiras e Enforcadores'],
  ],
];

const croCatMock = [
  [
    '1679',
    'Ração',
    ['Ração Seca', 'Ração Úmida', 'Ração Prescrita', 'Ração Natural'],
  ],
  ['1684', 'Petiscos', ['Biscoitos', 'Bifinhos']],
  [
    '1687',
    'Areias e Banheiros',
    [
      'Areias',
      'Sílica',
      'Caixas de Areia',
      'Banheiros',
      'Acessórios Sanitários',
    ],
  ],
  [
    '1693',
    'Farmácia',
    [
      'Antipulgas e Carrapatos',
      'Vermífugos',
      'Suplementos e Vitaminas',
      'Antibióticos',
      'Anti-inflamatórios',
      'Banho Terapêutico',
      'Colares Elizabetanos',
      'Homeopáticos e Florais',
      'Demais Medicamentos',
      'Oftalmológicos',
      'Otológicos',
      'Roupas Cirúrgicas',
    ],
  ],
  [
    '1706',
    'Arranhadores e Brinquedos',
    [
      'Arranhadores',
      'Brinquedos com Erva do Gato',
      'Brinquedos Educativos',
      'Ratinhos e Bolinhas',
      'Varinhas',
    ],
  ],
  [
    '1712',
    'Beleza e Limpeza',
    [
      'Alicates e Tesouras',
      'Banho à Seco e Talcos',
      'Higiene Bucal',
      'Lenços Umedecidos',
      'Limpeza de Olhos e Ouvidos',
      'Máquina de Tosa e Acessórios',
      'Pentes, escovas e Rasqueadeiras',
      'Perfumes e Colônias',
      'Sabonetes',
      'Shampoos e Condicionadores',
      'Hidratantes',
      'Eliminador de Odores e Desinfetantes',
      'Educadores, Repelentes e Atrativos',
    ],
  ],
  ['1726', 'Coleiras e Peitorais', ['Coleiras', 'Peitorais']],
  [
    '1730',
    'Acessórios de Alimentação',
    [
      'Bebedouros',
      'Comedouros',
      'Fontes',
      'Jogo Americano',
      'Mamadeiras',
      'Porta Ração',
      'Dosadores de Ração',
    ],
  ],
  [
    '1738',
    'Acessórios de Transporte',
    [
      'Caixas de Transporte',
      'Bolsas de Transporte',
      'Cadeirinhas',
      'Cintos de Segurança',
      'Capas para Banco de Carro',
      'Carrinhos',
    ],
  ],
  ['1745', 'Camas, Almofadas e Tocas', ['Camas', 'Tocas', 'Almofadas']],
  ['1749', 'Roupas', ['Roupas de Inverno', 'Roupas de Verão']],
];

const croBirdMock = [
  [
    '1601',
    'Alimentação',
    [
      'Calopsita',
      'Trinca-Ferro',
      'Papagaio',
      'Periquito',
      'Beija-Flor',
      'Sabiá',
      'Canário',
      'Outras Espécies',
    ],
  ],
  ['1610', 'Gaiolas e Viveiros', ['Gaiolas', 'Viveiros']],
  ['1613', 'Brinquedos e Poleiros', ['Brinquedos', 'Poleiros']],
  [
    '1616',
    'Acessórios',
    [
      'Porta Frutas e Porta Vitaminas',
      'Bebedouros',
      'Comedouros',
      'Banheiras',
      'Ninhos',
      'Bica Pedra',
      'Higiene',
    ],
  ],
  [
    '1624',
    'Farmácia',
    ['Vitaminas', 'Vermífugos', 'Antibióticos', 'Medicamentos'],
  ],
];

const croFishMock = [
  [
    '1635',
    'Alimentação',
    [
      'Alimento Base',
      'Peixes de Fundo',
      'Peixe Betta',
      'Ciclídeos',
      'Kinguios e Carpas',
      'Peixes Carnívoros',
      'Peixes Marinhos',
      'Outras Espécies',
    ],
  ],
  [
    '1644',
    'Equipamentos e Acessórios',
    [
      'Alimentador Automático',
      'Filtros e Mídias',
      'Iluminação',
      'Bombas e Compressores',
      'Termostatos e Termômetros',
      'Aquecedores',
      'Sifão',
      'Limpadores',
      'Criadeiras',
    ],
  ],
  ['1654', 'Aquários e Beteiras', ['Aquário Kit', 'Aquário Base', 'Beteiras']],
  ['1658', 'Tratamento de Água', ['Condicionador de Água', 'Testes de Água']],
  ['1661', 'Decoração', ['Substratos', 'Rochas e Troncos', 'Enfeites']],
  ['1665', 'Farmácia', ['Suplementos', 'Medicamentos']],
];

const croOtherPetsMock = [
  [
    '1534',
    'Coelhos',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Feno e Alfafa',
      'Brinquedos',
      'Higiene',
      'Medicamentos e Vitaminas',
      'Acessórios',
    ],
  ],
  [
    '1543',
    'Hamster e Twister',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Feno e Alfafa',
      'Medicamentos e Vitaminas',
      'Brinquedos',
      'Higiene',
      'Acessórios',
    ],
  ],
  [
    '1552',
    'Porquinho da Índia',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Feno e Alfafa',
      'Medicamentos e Vitaminas',
      'Brinquedos',
      'Higiene',
      'Acessórios',
    ],
  ],
  [
    '1561',
    'Chinchilas',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Feno e Alfafa',
      'Brinquedos',
      'Medicamentos e Vitaminas',
      'Higiene',
      'Acessórios',
    ],
  ],
  [
    '1570',
    'Gerbil',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Feno e Alfafa',
      'Brinquedos',
      'Medicamentos e Vitaminas',
      'Acessórios',
    ],
  ],
  [
    '1578',
    'Furão',
    [
      'Ração',
      'Gaiolas e Casinhas',
      'Serragens e Granulados',
      'Medicamentos e Vitaminas',
      'Acessórios',
    ],
  ],
  [
    '1584',
    'Tartarugas',
    [
      'Ração',
      'Aquaterrários',
      'Medicamentos e Vitaminas',
      'Tocas',
      'Acessórios',
    ],
  ],
  [
    '1590',
    'Lagartos',
    [
      'Ração',
      'Aquaterrários',
      'Medicamentos e Vitaminas',
      'Tocas',
      'Acessórios',
    ],
  ],
];

const croHouseGardenMock = [
  [
    '1438',
    'Jardim',
    [
      'Semente',
      'Vasos e Pratos',
      'Terras e Substratos',
      'Adubos e Fertilizantes',
      'Enfeites e Decorações',
      'Regadores e Pulverizadores',
      'Acessórios de Jardinagem',
    ],
  ],
  [
    '1446',
    'Piscina',
    [
      'Cloro para Piscina',
      'Algicidas',
      'Clarificantes',
      'Decantador',
      'Limpa Bordas',
      'Regulador de PH',
      'Teste de Piscina',
    ],
  ],
  ['1454', 'Controle de Pragas', ['Raticidas', 'Repelentes', 'Inseticidas']],
  ['1458', 'Casa e Ambiente', ['Aromatizadores e Difusores', 'Diversos']],
  ['1461', 'Livros e Presentes', ['Livros', 'Presentes']],
  ['2616', 'Conveniência', ['Acessórios para Celular']],
];

const categoryData = [
  {
    id: '1766',
    title: 'Cachorros',
    slug: 'cachorro',
    src: 'cachorros',
    color: '',
    mock: croDogMock,
  },
  {
    id: '1678',
    title: 'Gatos',
    slug: 'gato',
    src: 'gatos',
    color: 'skin',
    mock: croCatMock,
  },
  {
    id: '1600',
    title: 'Pássaros',
    slug: 'passaros',
    src: 'passaros',
    color: 'green',
    mock: croBirdMock,
  },
  {
    id: '1634',
    title: 'Peixes',
    slug: 'peixes',
    src: 'peixes',
    color: 'blue',
    mock: croFishMock,
  },
  {
    id: '1533',
    title: 'Outros Pets',
    slug: 'outros-pets',
    src: 'outros',
    color: 'heavy-skin',
    mock: croOtherPetsMock,
  },
  {
    id: '1437',
    title: 'Casa e Jardim',
    slug: 'casa-e-jardim',
    src: 'casa-jardim',
    color: 'green-forest',
    mock: croHouseGardenMock,
  },
];
